import Head from 'next/head'
import Navigation from '@/components/Navigation'

export default function Home() {
  return (
    <>
      <Head>
        <title>Renato Brito // Portfólio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main>
        <hr />
        <h1>Estou na HOME</h1>
      </main>
    </>
  )
}
